-- MySQL Script generated by MySQL Workbench
-- Mon Apr  3 23:44:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema techmaster_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema techmaster_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `techmaster_db` DEFAULT CHARACTER SET utf8 ;
USE `techmaster_db` ;

-- -----------------------------------------------------
-- Table `techmaster_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techmaster_db`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techmaster_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techmaster_db`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(245) NOT NULL,
  `price` INT NULL,
  `description` TEXT NULL,
  `discount` INT NULL,
  `categoryId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_products_categories1_idx` (`categoryId` ASC) VISIBLE,
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`categoryId`)
    REFERENCES `techmaster_db`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techmaster_db`.`rols`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techmaster_db`.`rols` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techmaster_db`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techmaster_db`.`locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `zipCode` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techmaster_db`.`avatars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techmaster_db`.`avatars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techmaster_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techmaster_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `rolId` INT NOT NULL,
  `location_id` INT NOT NULL,
  `avatars_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_users_rols1_idx` (`rolId` ASC) VISIBLE,
  INDEX `fk_users_location1_idx` (`location_id` ASC) VISIBLE,
  INDEX `fk_users_avatars1_idx` (`avatars_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_rols1`
    FOREIGN KEY (`rolId`)
    REFERENCES `techmaster_db`.`rols` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `techmaster_db`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_avatars1`
    FOREIGN KEY (`avatars_id`)
    REFERENCES `techmaster_db`.`avatars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techmaster_db`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techmaster_db`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(245) NOT NULL,
  `productsId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_images_products_idx` (`productsId` ASC) VISIBLE,
  CONSTRAINT `fk_images_products`
    FOREIGN KEY (`productsId`)
    REFERENCES `techmaster_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techmaster_db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techmaster_db`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_orders_users1_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `techmaster_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techmaster_db`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techmaster_db`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `productsId` INT NOT NULL,
  `orders_id` INT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_carts_products1_idx` (`productsId` ASC) VISIBLE,
  INDEX `fk_carts_orders1_idx` (`orders_id` ASC) VISIBLE,
  CONSTRAINT `fk_carts_products1`
    FOREIGN KEY (`productsId`)
    REFERENCES `techmaster_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carts_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `techmaster_db`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
